name: XQuarz

on: [pull_request]

jobs:
  build-XQuarz:
    name: build
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: [Xcode_12.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Set XCode Version
        run: sudo xcode-select -s /Applications/${{ matrix.xcode }}.app
      - name: pre build
        run: ./install-or-update-macports.sh
      - name: Build project
        run: ./compile.sh
